# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-21 23:06
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_auto_20181021_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
